import { NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

// Force dynamic rendering to prevent build-time evaluation
export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    // Initialize Resend with API key from environment variable
    const resend = new Resend(process.env.RESEND_API_KEY || "")

    const data = await request.json()
    const {
      name,
      phone,
      email,
      address,
      city,
      state,
      zip,
      pestIssue,
      urgency,
      preferredContact,
    } = data

    const urgencyEmoji = urgency === "emergency" ? "🚨" : urgency === "urgent" ? "⚠️" : "📋"

    // Send notification email to business
    await resend.emails.send({
      from: "Preventive Pest Control <onboarding@resend.dev>",
      to: process.env.CONTACT_EMAIL || "info@preventivepestcontrol.com",
      subject: `${urgencyEmoji} New Service Request: ${name} - ${pestIssue}`,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 0 auto; padding: 20px; }
              .header { background: linear-gradient(135deg, #16a34a 0%, #15803d 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; }
              .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
              .field { margin-bottom: 20px; }
              .label { font-weight: bold; color: #16a34a; margin-bottom: 5px; }
              .value { background: white; padding: 12px; border-left: 3px solid #16a34a; margin-top: 5px; }
              .urgent { background: #fee2e2; border-left-color: #dc2626; }
              .footer { text-align: center; margin-top: 20px; font-size: 12px; color: #666; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1 style="margin: 0; font-size: 24px;">🕷️ New Service Request</h1>
                <p style="margin: 10px 0 0 0; opacity: 0.9;">From Peter the Chatbot</p>
              </div>
              <div class="content">
                <div class="field">
                  <div class="label">Customer Name</div>
                  <div class="value">${name}</div>
                </div>

                <div class="field">
                  <div class="label">Phone Number</div>
                  <div class="value">${phone}</div>
                </div>

                ${
                  email
                    ? `
                <div class="field">
                  <div class="label">Email Address</div>
                  <div class="value">${email}</div>
                </div>
                `
                    : ""
                }

                <div class="field">
                  <div class="label">Service Address</div>
                  <div class="value">
                    ${address}<br>
                    ${city}, ${state} ${zip}
                  </div>
                </div>

                <div class="field">
                  <div class="label">Pest Issue</div>
                  <div class="value">${pestIssue}</div>
                </div>

                <div class="field">
                  <div class="label">Urgency Level</div>
                  <div class="value ${urgency === "emergency" || urgency === "urgent" ? "urgent" : ""}">
                    ${urgencyEmoji} ${urgency.toUpperCase()}
                    ${urgency === "emergency" ? " - CALL IMMEDIATELY" : ""}
                    ${urgency === "urgent" ? " - Priority Response" : ""}
                  </div>
                </div>

                <div class="field">
                  <div class="label">Preferred Contact Method</div>
                  <div class="value">${preferredContact === "phone" ? "📞 Phone Call" : preferredContact === "text" ? "💬 Text Message" : "📧 Email"}</div>
                </div>

                <div style="margin-top: 30px; padding: 20px; background: #dbeafe; border-radius: 8px;">
                  <p style="margin: 0; font-weight: bold; color: #1e40af;">⏰ Response Time:</p>
                  <p style="margin: 5px 0 0 0; color: #1e40af;">
                    ${urgency === "emergency" ? "Contact customer IMMEDIATELY" : urgency === "urgent" ? "Within 1-2 hours" : "Within 24 hours"}
                  </p>
                </div>
              </div>
              <div class="footer">
                <p>This lead was generated by Peter the AI chatbot on preventivepestcontrol.com</p>
              </div>
            </div>
          </body>
        </html>
      `,
    })

    // Send confirmation email to customer (if email provided)
    if (email) {
      await resend.emails.send({
        from: "Preventive Pest Control <onboarding@resend.dev>",
        to: email,
        subject: "Service Request Received - Preventive Pest Control",
        html: `
          <!DOCTYPE html>
          <html>
            <head>
              <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: linear-gradient(135deg, #16a34a 0%, #15803d 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
                .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
                .highlight { background: #dcfce7; padding: 15px; border-radius: 8px; margin: 20px 0; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1 style="margin: 0; font-size: 28px;">🕷️ Thanks ${name}!</h1>
                  <p style="margin: 10px 0 0 0; opacity: 0.9;">We received your service request</p>
                </div>
                <div class="content">
                  <p>Hi ${name},</p>
                  <p>Thanks for choosing Preventive Pest Control! We received your request for ${pestIssue} service.</p>

                  <div class="highlight">
                    <p style="margin: 0; font-weight: bold; color: #16a34a;">✅ What's Next:</p>
                    <ul style="margin: 10px 0 0 0; padding-left: 20px;">
                      <li>We'll contact you ${urgency === "emergency" ? "within minutes" : urgency === "urgent" ? "within 1-2 hours" : "within 24 hours"}</li>
                      <li>Schedule your free inspection</li>
                      <li>Get your $39.95 first service</li>
                    </ul>
                  </div>

                  <p><strong>Service Address:</strong><br>
                  ${address}<br>
                  ${city}, ${state} ${zip}</p>

                  <p><strong>Contact Info:</strong><br>
                  Phone: ${phone}<br>
                  ${email ? `Email: ${email}` : ""}</p>

                  <p style="margin-top: 30px;">Have questions? Call us anytime at <strong>(435) 256-6391</strong></p>

                  <p style="margin-top: 30px; color: #666; font-size: 14px;">
                    Thanks,<br>
                    <strong>The Preventive Pest Control Team</strong><br>
                    St. George's Top Pest Control Professionals
                  </p>
                </div>
              </div>
            </body>
          </html>
        `,
      })
    }

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error("Schedule API error:", error)
    return NextResponse.json({ success: false, error: "Failed to process request" }, { status: 500 })
  }
}
